
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aeclpuhqkoobrfodtpxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlY2xwdWhxa29vYnJmb2R0cHhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NjY1NDAsImV4cCI6MjA1ODU0MjU0MH0.L7oYYXfI6jc0ykjv9jdzTuC2kd6hbekMhlP9Wq5TmPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
